" Load the other 'vimrc' files
source ./vimrc_vundle

:syntax on        " enable syntax high-lighting
:set number       " enable line numbers 
set textwidth=99  " lines longer than 99 columns will be broken
set tabstop=2     " set each tab to width two
set shiftwidth=2  " operation >> indents 2 columns; << unindents 2 columns
set softtabstop=2 " insert/delete 4 spaces when hitting a TAB/BACKSPACE
set ruler         " show column
set sw=2          " set shift width to two
:set et           " convert tabs to spaces (short for expandtabs)
set backspace=indent,eol,start " enable sensible back-space behavior
set expandtab     " insert spaces when hitting TABs
set shiftround    " round indent to multiple of 'shiftwidth'
set autoindent
" Set a highlight over text on lines over n column chars.
highlight OverLength ctermbg=blue ctermfg=white guibg=#592929
match OverLength /\%101v.\+/
set directory=/tmp " vim swap files get put here.
