set nocompatible " Unset compatibility with VI, it's 2014!
" Load the other 'vimrc' files
source ~/.vim/vimrc_vundle

syntax on        " enable syntax high-lighting
set background=dark
let g:solarized_termcolors=256
colorscheme solarized
set number       " enable line numbers 
set nowrap        " Don't column wrap the text
set showmatch     " Show matching brackets
set ignorecase    " Do case insensitive matching
set textwidth=99  " lines longer than 99 columns will be broken
set tabstop=2     " set each tab to width two
set shiftwidth=2  " operation >> indents 2 columns; << unindents 2 columns
set softtabstop=2 " insert/delete 4 spaces when hitting a TAB/BACKSPACE
set ruler         " show column
set sw=2          " set shift width to two
set et           " convert tabs to spaces (short for expandtabs)
set backspace=indent,eol,start " enable sensible back-space behavior
set expandtab     " insert spaces when hitting TABs
set shiftround    " round indent to multiple of 'shiftwidth'
set autoindent

" Remap some keys to be less button presses! Thanks Phil
nmap ;s :sp .<CR>
nmap ;v :vsp .<CR>
nmap ;l :set invnumber<CR>
nmap ;x :x<CR>
nmap ;w :w<CR>
nmap ;q :q!<CR>
" Remap opening NERDTree to something easier
nmap ;n :NERDTree<CR>
" map new escape in insert and visual modes
inoremap ;w <ESC>:w<CR>
inoremap ;x <ESC>:x<CR>
inoremap ;q <ESC>:q<CR>

" These two remap the '`' and the escape keys to refer to one another.
inoremap ` <ESC>
cnoremap ` <ESC>
vnoremap ` <ESC>

inoremap <ESC> `
cnoremap <ESC> `
vnoremap <ESC> `
" timeout between mapped keypresses
set timeoutlen=200

" http://bpdp.blogspot.com/2012/01/arrows-problem-in-nerdtree-vim-plugin.html
let g:NERDTreeDirArrows=0

" Set a highlight over text on lines over n column chars.
highlight OverLength ctermbg=blue ctermfg=white guibg=#592929
match OverLength /\%101v.\+/

set directory=/tmp " vim swap files get put here.
set shell=/bin/bash " This is to work-around a bug in vundle with the fish terminal.
